[DEFAULT]
api_config = "early-access"
verbose = true
storage_config = "early-access-azure"

[trigger]
poll_period = 3600
startup_delay = 3
build_configs = "mainline"

[tarball]
kdir = "/home/kernelci/pipeline/data/src/linux"
output = "/home/kernelci/pipeline/data/output"
