# SPDX-License-Identifier: LGPL-2.1-or-later
#
# Copyright (C) 2021 Collabora Limited
# Author: Guillaume Tucker <guillaume.tucker@collabora.com>

version: '3'

services:

  notifier: &base-service
    container_name: 'notifier'
    build:
      context: docker
    env_file:
      - .env
    command:
      - './pipeline/notifier.py'
      - '--settings=/home/kernelci/config/kernelci.conf'
      - 'run'
    stop_signal: SIGINT
    volumes:
      - './src:/home/kernelci/pipeline'
      - './config:/home/kernelci/config'
      - './data:/home/kernelci/data'

  runner:
    <<: *base-service
    container_name: 'runner'
    command:
      - './pipeline/runner.py'
      - '--settings=/home/kernelci/config/kernelci.conf'
      - 'run'

  tarball:
    <<: *base-service
    container_name: 'tarball'
    command:
      - './pipeline/tarball.py'
      - '--settings=/home/kernelci/config/kernelci.conf'
      - 'run'

  trigger:
    <<: *base-service
    container_name: 'trigger'
    command:
      - './pipeline/trigger.py'
      - '--settings=/home/kernelci/config/kernelci.conf'
      - 'run'

  kcidb:
    <<: *base-service
    container_name: 'kcidb'
    command:
      - '/usr/bin/env'
      - 'python3'
      - '/home/kernelci/pipeline/kcidb.py'
      - '--settings=/home/kernelci/config/kernelci.conf'
      - 'run'
