# SPDX-License-Identifier: LGPL-2.1-or-later
#
# Copyright (C) 2021, 2022 Collabora Limited
# Author: Guillaume Tucker <guillaume.tucker@collabora.com>

version: '3'

services:

  notifier: &base-service
    container_name: 'kernelci-pipeline-notifier'
    image: 'kernelci/staging-kernelci'
    env_file: ['.env']
    stop_signal: 'SIGINT'
    command:
      - './pipeline/notifier.py'
      - '--settings=${SETTINGS:-/home/kernelci/config/kernelci.conf}'
      - 'run'
    volumes: &base-volumes
      - './src:/home/kernelci/pipeline'
      - './config:/home/kernelci/config'

  runner: &runner
    container_name: 'kernelci-pipeline-runner'
    image: 'kernelci/staging-kernelci'
    env_file: ['.env']
    stop_signal: 'SIGINT'
    command:
      - './pipeline/runner.py'
      - '--settings=${SETTINGS:-/home/kernelci/config/kernelci.conf}'
      - 'loop'
      - '--lab-config=shell'
      - '--plan=kver'
    volumes:
      - './src:/home/kernelci/pipeline'
      - './config:/home/kernelci/config'
      - './data/output:/home/kernelci/output'
      - './data/k8s-credentials/.kube:/home/kernelci/.kube'
      - './data/k8s-credentials/.config/gcloud:/home/kernelci/.config/gcloud'
      - './data/k8s-credentials/.azure:/home/kernelci/.azure'

  runner-k8s:
    <<: *runner
    container_name: 'kernelci-pipeline-runner-k8s'
    image: 'kernelci/staging-k8s:kernelci'
    command:
      - './pipeline/runner.py'
      - '--settings=${SETTINGS:-/home/kernelci/config/kernelci.conf}'
      - 'loop'
      - '--lab-config=k8s-gke-eu-west4'
      - '--plan=kunit'

  tarball:
    <<: *base-service
    container_name: 'kernelci-pipeline-tarball'
    command:
      - './pipeline/tarball.py'
      - '--settings=${SETTINGS:-/home/kernelci/config/kernelci.conf}'
      - 'run'
    volumes:
      - './src:/home/kernelci/pipeline'
      - './config:/home/kernelci/config'
      - './data/ssh:/home/kernelci/data/ssh'
      - './data/src:/home/kernelci/data/src'
      - './data/output:/home/kernelci/data/output'

  trigger:
    <<: *base-service
    container_name: 'kernelci-pipeline-trigger'
    command:
      - './pipeline/trigger.py'
      - '--settings=${SETTINGS:-/home/kernelci/config/kernelci.conf}'
      - 'run'

  complete-hack:
    <<: *base-service
    container_name: 'kernelci-pipeline-complete-hack'
    command:
      - './pipeline/complete_hack.py'
      - '--settings=${SETTINGS:-/home/kernelci/config/kernelci.conf}'
      - 'run'

  kcidb:
    container_name: 'kernelci-pipeline-kcidb'
    build: {context: 'docker-kcidb'}
    env_file: ['.env']
    stop_signal: 'SIGINT'
    command:
      - '/usr/bin/env'
      - 'python3'
      - '/home/kernelci/pipeline/send_kcidb.py'
      - '--settings=${SETTINGS:-/home/kernelci/config/kernelci.conf}'
      - 'run'
    volumes: *base-volumes

  test_report:
    <<: *base-service
    container_name: 'kernelci-pipeline-test_report'
    command:
      - '/usr/bin/env'
      - 'python3'
      - '/home/kernelci/pipeline/test_report.py'
      - '--settings=${SETTINGS:-/home/kernelci/config/kernelci.conf}'
      - 'run'

  set_complete:
    <<: *base-service
    container_name: 'kernelci-pipeline-set_complete'
    command:
      - '/usr/bin/env'
      - 'python3'
      - '/home/kernelci/pipeline/set_complete.py'
      - '--settings=/home/kernelci/config/kernelci.conf'
      - 'run'
  
  set_timeout:
    <<: *base-service
    container_name: 'kernelci-pipeline-set_timeout'
    command:
      - '/usr/bin/env'
      - 'python3'
      - '/home/kernelci/pipeline/set_timeout.py'
      - '--settings=${SETTINGS:-/home/kernelci/config/kernelci.conf}'
      - 'run'
