# SPDX-License-Identifier: LGPL-2.1-or-later
#
# Copyright (C) 2026 Linaro Limited

runtimes:

  pull-labs-demo:
    lab_type: pull_labs
    poll_interval: 45
    timeout: 7200
    storage_name: kci-storage
    notify:
      callback:
        token: kernelci-pull-labs-demo
