_anchors:

  arm64-chromebook-device: &arm64-chromebook-device
    arch: arm64
    boot_method: depthcharge
    params: &arm64-chromebook-device-params
      flash_kernel:
        url: https://storage.chromeos.kernelci.org/images/kernel/v6.1-{mach}
        image: 'kernel/Image'
      nfsroot: https://storage.chromeos.kernelci.org/images/rootfs/debian/bookworm-cros-flash/20240422.0/{debarch}
      tast_tarball: https://storage.chromeos.kernelci.org/images/rootfs/chromeos/chromiumos-{base_name}/20241031.0/{debarch}/tast.tgz
    rules: &arm64-chromebook-device-rules
      defconfig:
        - '!allnoconfig'
        - '!allmodconfig'
      fragments:
        - 'arm64-chromebook'

  x86-chromebook-device: &x86-chromebook-device
    arch: x86_64
    boot_method: depthcharge
    mach: x86
    params:
      <<: *arm64-chromebook-device-params
      flash_kernel:
        url: https://storage.chromeos.kernelci.org/images/kernel/cros-20230815-amd64/clang-14
        image: 'kernel/bzImage'
      tast_tarball: https://storage.chromeos.kernelci.org/images/rootfs/chromeos/chromiumos-{base_name}/20240918.0/{debarch}/tast.tgz
    rules: &x86-chromebook-device-rules
      <<: *arm64-chromebook-device-rules
      fragments:
        - 'x86-board'

platforms:
  acer-R721T-grunt: &chromebook-grunt-device
    <<: *x86-chromebook-device
    base_name: grunt
    rules:
      <<: *x86-chromebook-device-rules
      branch:
        - 'chromiumos:chromeos-5.10'
        - 'stable:linux-5.10.y'
        - 'stable:linux-6.12.y'
        - 'stable-rc:linux-5.10.y'
        - 'stable-rc:linux-6.12.y'

  acer-cb317-1h-c3z6-dedede:
    <<: *x86-chromebook-device
    base_name: dedede
    rules:
      <<: *x86-chromebook-device-rules
      branch:
        - 'chromiumos:chromeos-6.1'
        - 'stable:linux-6.1.y'
        - 'stable:linux-6.12.y'
        - 'stable-rc:linux-6.1.y'
        - 'stable-rc:linux-6.12.y'

  acer-cbv514-1h-34uz-brya:
    <<: *x86-chromebook-device
    base_name: brya
    rules:
      <<: *x86-chromebook-device-rules
      branch:
        - 'chromiumos:chromeos-6.6'
        - 'stable:linux-6.6.y'
        - 'stable:linux-6.12.y'
        - 'stable-rc:linux-6.6.y'
        - 'stable-rc:linux-6.12.y'

  acer-chromebox-cxi4-puff:
    <<: *x86-chromebook-device
    base_name: puff
    rules:
      <<: *x86-chromebook-device-rules
      branch:
        - 'chromiumos:chromeos-5.15'
        - 'stable:linux-5.15.y'
        - 'stable:linux-6.12.y'
        - 'stable-rc:linux-5.15.y'
        - 'stable-rc:linux-6.12.y'

  acer-chromebox-cxi5-brask:
    <<: *x86-chromebook-device
    base_name: brask
    rules:
      <<: *x86-chromebook-device-rules
      branch:
        - 'chromiumos:chromeos-6.6'
        - 'stable:linux-6.6.y'
        - 'stable:linux-6.12.y'
        - 'stable-rc:linux-6.6.y'
        - 'stable-rc:linux-6.12.y'

  acer-cp514-2h-1130g7-volteer: &chromebook-volteer-device
    <<: *x86-chromebook-device
    base_name: volteer
    rules:
      <<: *x86-chromebook-device-rules
      branch:
        - 'chromiumos:chromeos-5.4'
        - 'stable:linux-5.4.y'
        - 'stable:linux-6.12.y'
        - 'stable-rc:linux-5.4.y'
        - 'stable-rc:linux-6.12.y'

  acer-cp514-2h-1160g7-volteer: *chromebook-volteer-device

  acer-cp514-3wh-r0qs-guybrush:
    <<: *x86-chromebook-device
    base_name: guybrush
    rules:
      <<: *x86-chromebook-device-rules
      branch:
        - 'chromiumos:chromeos-6.6'
        - 'stable:linux-6.6.y'
        - 'stable:linux-6.12.y'
        - 'stable-rc:linux-6.6.y'
        - 'stable-rc:linux-6.12.y'

  acer-n20q11-r856ltn-p1s2-nissa:
    <<: *x86-chromebook-device
    base_name: nissa
    rules:
      <<: *x86-chromebook-device-rules
      branch:
        - 'chromiumos:chromeos-6.6'
        - 'stable:linux-6.6.y'
        - 'stable:linux-6.12.y'
        - 'stable-rc:linux-6.6.y'
        - 'stable-rc:linux-6.12.y'

  asus-C433TA-AJ0005-rammus:
    <<: *x86-chromebook-device
    base_name: rammus
    rules:
      <<: *x86-chromebook-device-rules
      branch:
        - 'chromiumos:chromeos-5.10'
        - 'stable:linux-5.10.y'
        - 'stable:linux-6.12.y'
        - 'stable-rc:linux-5.10.y'
        - 'stable-rc:linux-6.12.y'

  asus-C436FA-Flip-hatch:
    <<: *x86-chromebook-device
    base_name: hatch
    rules:
      <<: *x86-chromebook-device-rules
      branch:
        - 'chromiumos:chromeos-5.15'
        - 'stable:linux-5.15.y'
        - 'stable:linux-6.12.y'
        - 'stable-rc:linux-5.15.y'
        - 'stable-rc:linux-6.12.y'

  asus-C523NA-A20057-coral:
    <<: *x86-chromebook-device
    base_name: coral
    rules:
      <<: *x86-chromebook-device-rules
      branch:
        - 'chromiumos:chromeos-5.10'
        - 'stable:linux-5.10.y'
        - 'stable:linux-6.12.y'
        - 'stable-rc:linux-5.10.y'
        - 'stable-rc:linux-6.12.y'

  asus-CM1400CXA-dalboz: &chromebook-zork-device
    <<: *x86-chromebook-device
    base_name: zork
    rules:
      <<: *x86-chromebook-device-rules
      branch:
        - 'chromiumos:chromeos-5.4'
        - 'stable:linux-5.4.y'
        - 'stable:linux-6.12.y'
        - 'stable-rc:linux-5.4.y'
        - 'stable-rc:linux-6.12.y'

  dell-latitude-3445-7520c-skyrim:
    <<: *x86-chromebook-device
    base_name: skyrim
    rules:
      <<: *x86-chromebook-device-rules
      branch:
        - 'chromiumos:chromeos-6.6'
        - 'stable:linux-6.6.y'
        - 'stable:linux-6.12.y'
        - 'stable-rc:linux-6.6.y'
        - 'stable-rc:linux-6.12.y'

  dell-latitude-5300-8145U-arcada: &chromebook-sarien-device
    <<: *x86-chromebook-device
    base_name: sarien
    rules:
      <<: *x86-chromebook-device-rules
      branch:
        - 'chromiumos:chromeos-5.10'
        - 'stable:linux-5.10.y'
        - 'stable:linux-6.12.y'
        - 'stable-rc:linux-5.10.y'
        - 'stable-rc:linux-6.12.y'

  dell-latitude-5400-4305U-sarien: *chromebook-sarien-device
  dell-latitude-5400-8665U-sarien: *chromebook-sarien-device
  hp-14-db0003na-grunt: *chromebook-grunt-device
  hp-11A-G6-EE-grunt: *chromebook-grunt-device
  hp-14b-na0052xx-zork: *chromebook-zork-device

  hp-x360-14-G1-sona:
    <<: *x86-chromebook-device
    base_name: nami
    rules:
      <<: *x86-chromebook-device-rules
      branch:
        - 'chromiumos:chromeos-5.4'
        - 'stable:linux-5.4.y'
        - 'stable:linux-6.12.y'
        - 'stable-rc:linux-5.4.y'
        - 'stable-rc:linux-6.12.y'

  hp-x360-12b-ca0010nr-n4020-octopus:
    <<: *x86-chromebook-device
    base_name: octopus
    rules:
      <<: *x86-chromebook-device-rules
      branch:
        - 'chromiumos:chromeos-5.15'
        - 'stable:linux-5.15.y'
        - 'stable:linux-6.12.y'
        - 'stable-rc:linux-5.15.y'
        - 'stable-rc:linux-6.12.y'

  hp-x360-14a-cb0001xx-zork: *chromebook-zork-device
  lenovo-TPad-C13-Yoga-zork: *chromebook-zork-device

  mt8173-elm-hana: &mediatek-chromebook-device
    <<: *arm64-chromebook-device
    base_name: hana
    mach: mediatek
    dtb: dtbs/mediatek/mt8173-elm-hana.dtb
    compatible: ['google,hana-rev6', 'google,hana-rev5', 'google,hana-rev4', 'google,hana-rev3', 'google,hana', 'mediatek,mt8173']
    context:
      test_character_delay: 10
    rules:
      <<: *arm64-chromebook-device-rules
      branch:
        - 'chromiumos:chromeos-5.15'
        - 'stable:linux-5.15.y'
        - 'stable:linux-6.1.y'
        - 'stable:linux-6.6.y'
        - 'stable:linux-6.12.y'
        - 'stable-rc:linux-5.15.y'
        - 'stable-rc:linux-6.1.y'
        - 'stable-rc:linux-6.6.y'
        - 'stable-rc:linux-6.12.y'

  mt8183-kukui-jacuzzi-juniper-sku16:
    <<: *mediatek-chromebook-device
    base_name: jacuzzi
    dtb: dtbs/mediatek/mt8183-kukui-jacuzzi-juniper-sku16.dtb
    compatible: ['google,juniper-sku16', 'google,juniper', 'mediatek,mt8183']
    rules:
      <<: *arm64-chromebook-device-rules
      branch:
        - 'chromiumos:chromeos-5.10'
        - 'stable:linux-6.1.y'
        - 'stable:linux-6.6.y'
        - 'stable:linux-6.12.y'
        - 'stable-rc:linux-6.1.y'
        - 'stable-rc:linux-6.6.y'
        - 'stable-rc:linux-6.12.y'

  mt8186-corsola-steelix-sku131072:
    <<: *mediatek-chromebook-device
    base_name: corsola
    dtb: dtbs/mediatek/mt8186-corsola-steelix-sku131072.dtb
    compatible: ['google,steelix-sku131072', 'google,steelix']
    params:
      <<: *arm64-chromebook-device-params
      flash_kernel:
        url: https://storage.chromeos.kernelci.org/images/kernel/v6.10-mediatek/
        image: 'Image'
    rules:
      <<: *arm64-chromebook-device-rules
      branch:
        - 'chromiumos:chromeos-5.15'
        - 'stable:linux-6.12.y'
        - 'stable-rc:linux-6.12.y'

  mt8192-asurada-spherion-r0:
    <<: *mediatek-chromebook-device
    base_name: asurada
    dtb: dtbs/mediatek/mt8192-asurada-spherion-r0.dtb
    compatible: ['google,spherion-rev3', 'google,spherion-rev2']
    rules:
      <<: *arm64-chromebook-device-rules
      branch:
        - 'chromiumos:chromeos-6.1'
        - 'stable:linux-6.6.y'
        - 'stable:linux-6.12.y'
        - 'stable-rc:linux-6.6.y'
        - 'stable-rc:linux-6.12.y'

  mt8195-cherry-tomato-r2:
    <<: *mediatek-chromebook-device
    base_name: cherry-r2
    dtb:
      - 'dtbs/mediatek/mt8195-cherry-tomato-r2.dtb'
      - 'dtbs/mediatek/mt8195-tomato-rev2.dtb'
    compatible: ['google,tomato-rev2', 'google,tomato', 'mediatek,mt8195']
    rules:
      <<: *arm64-chromebook-device-rules
      branch:
        - 'chromiumos:chromeos-5.10'
        - 'stable:linux-6.6.y'
        - 'stable:linux-6.12.y'
        - 'stable-rc:linux-6.6.y'
        - 'stable-rc:linux-6.12.y'

  mt8195-cherry-tomato-r3:
    <<: *mediatek-chromebook-device
    base_name: cherry-r3
    dtb:
      - 'dtbs/mediatek/mt8195-cherry-tomato-r3.dtb'
      - 'dtbs/mediatek/mt8195-tomato-rev3.dtb'
    compatible: ['google,tomato-rev4', 'google,tomato-rev3','google,tomato', 'mediatek,mt8195']
    rules:
      <<: *arm64-chromebook-device-rules
      branch:
        - 'chromiumos:chromeos-5.10'
        - 'stable:linux-6.6.y'
        - 'stable:linux-6.12.y'
        - 'stable-rc:linux-6.6.y'
        - 'stable-rc:linux-6.12.y'

  sc7180-trogdor-kingoftown: &trogdor-chromebook-device
    <<: *arm64-chromebook-device
    base_name: trogdor
    mach: qcom
    dtb:
      - dtbs/qcom/sc7180-trogdor-kingoftown.dtb
      - dtbs/qcom/sc7180-trogdor-kingoftown-r1.dtb
    compatible: ['google,kingoftown', 'qcom,sc7180']
    params:
      <<: *arm64-chromebook-device-params
      flash_kernel:
        url: https://storage.chromeos.kernelci.org/images/kernel/v6.1-qualcomm
        image: 'kernel/Image'
        dtb: 'dtbs/qcom/sc7180-trogdor-kingoftown-r1.dtb'
    rules:
      branch:
        - 'chromiumos:chromeos-6.6'
        - 'stable:linux-6.6.y'
        - 'stable:linux-6.12.y'
        - 'stable-rc:linux-6.6.y'
        - 'stable-rc:linux-6.12.y'

  sc7180-trogdor-lazor-limozeen:
    <<: *trogdor-chromebook-device
    dtb: dtbs/qcom/sc7180-trogdor-lazor-limozeen-nots-r5.dtb
    compatible: ['google,lazor-rev5-sku5', 'google,lazor-rev5-sku6']
