_anchors:
  build-k8s-all: &build-k8s-all
    event: &checkout-event
      channel: node
      kind: checkout
      state: available
    runtime:
      name: k8s-all

  node-event: &node-event-kbuild
    channel: node
    kind: kbuild
    state: available

  job-event: &job-event
    channel: node
    state: done
    kind: job

scheduler:

# start of CIP arm64 scheduler
  - job: baseline-arm64
    event: &kbuild-gcc-14-arm64-node-event
      <<: *node-event-kbuild
      name: kbuild-gcc-14-arm64
    runtime: &lava-cip-runtime
      type: lava
      name: lava-cip
    platforms: &cip-arm64-platforms
      - qemu-arm64
      - r8a774a1-hihope-rzg2m-ex
      - zynqmp-zcu102

  - job: job-gcc-14-arm64-612-cip
    event:
      <<: *kbuild-gcc-14-arm64-node-event
      name: kbuild-gcc-14-arm64-612-cip
    runtime: *lava-cip-runtime
    platforms: *cip-arm64-platforms

  - &job-gcc-14-arm64-612-cip-rt
    job: job-gcc-14-arm64-612-cip-rt
    event:
      <<: *kbuild-gcc-14-arm64-node-event
      name: kbuild-gcc-14-arm64-612-cip-rt
    runtime: *lava-cip-runtime
    platforms: *cip-arm64-platforms

  - <<: *job-gcc-14-arm64-612-cip-rt
    job: rt-tests-cyclicdeadline

  - <<: *job-gcc-14-arm64-612-cip-rt
    job: rt-tests-cyclictest

  - job: job-gcc-14-arm64-61-cip
    event:
      <<: *kbuild-gcc-14-arm64-node-event
      name: kbuild-gcc-14-arm64-61-cip
    runtime: *lava-cip-runtime
    platforms: *cip-arm64-platforms

  - &job-gcc-14-arm64-61-cip-rt
    job: job-gcc-14-arm64-61-cip-rt
    event:
      <<: *kbuild-gcc-14-arm64-node-event
      name: kbuild-gcc-14-arm64-61-cip-rt
    runtime: *lava-cip-runtime
    platforms: *cip-arm64-platforms

  - <<: *job-gcc-14-arm64-61-cip-rt
    job: rt-tests-cyclicdeadline

  - <<: *job-gcc-14-arm64-61-cip-rt
    job: rt-tests-cyclictest

  - job: job-gcc-14-arm64-510-cip
    event:
      <<: *kbuild-gcc-14-arm64-node-event
      name: kbuild-gcc-14-arm64-510-cip
    runtime: *lava-cip-runtime
    platforms: *cip-arm64-platforms

  - &job-gcc-14-arm64-510-cip-rt
    job: job-gcc-14-arm64-510-cip-rt
    event:
      <<: *kbuild-gcc-14-arm64-node-event
      name: kbuild-gcc-14-arm64-510-cip-rt
    runtime: *lava-cip-runtime
    platforms: *cip-arm64-platforms

  - <<: *job-gcc-14-arm64-510-cip-rt
    job: rt-tests-cyclicdeadline

  - <<: *job-gcc-14-arm64-510-cip-rt
    job: rt-tests-cyclictest

  - job: job-gcc-14-arm64-419-cip
    event:
      <<: *kbuild-gcc-14-arm64-node-event
      name: kbuild-gcc-14-arm64-419-cip
    runtime: *lava-cip-runtime
    platforms: *cip-arm64-platforms

  - &job-gcc-14-arm64-419-cip-rt
    job: job-gcc-14-arm64-419-cip-rt
    event:
      <<: *kbuild-gcc-14-arm64-node-event
      name: kbuild-gcc-14-arm64-419-cip-rt
    runtime: *lava-cip-runtime
    platforms: *cip-arm64-platforms

  - <<: *job-gcc-14-arm64-419-cip-rt
    job: rt-tests-cyclicdeadline

  - <<: *job-gcc-14-arm64-419-cip-rt
    job: rt-tests-cyclictest

  - job: job-gcc-14-arm64-419-cip-st
    event:
      <<: *kbuild-gcc-14-arm64-node-event
      name: kbuild-gcc-14-arm64-419-cip-st
    runtime: *lava-cip-runtime
    platforms:
      - qemu-arm64
      - zynqmp-zcu102

  - job: kbuild-gcc-14-arm64-612-cip
    <<: *build-k8s-all

  - job: kbuild-gcc-14-arm64-612-cip-rt
    <<: *build-k8s-all

  - job: kbuild-gcc-14-arm64-61-cip
    <<: *build-k8s-all

  - job: kbuild-gcc-14-arm64-61-cip-rt
    <<: *build-k8s-all

  - job: kbuild-gcc-14-arm64-510-cip
    <<: *build-k8s-all

  - job: kbuild-gcc-14-arm64-510-cip-rt
    <<: *build-k8s-all

  - job: kbuild-gcc-14-arm64-419-cip
    <<: *build-k8s-all

  - job: kbuild-gcc-14-arm64-419-cip-rt
    <<: *build-k8s-all

  - job: kbuild-gcc-14-arm64-419-cip-st
    <<: *build-k8s-all

# start of CIP arm scheduler
  - job: baseline-arm
    event: &kbuild-gcc-14-arm-node-event
      <<: *node-event-kbuild
      name: kbuild-gcc-14-arm
    runtime: *lava-cip-runtime
    platforms: &cip-arm-platforms
      - beaglebone-black
      - de0-nano-soc
      - qemu-arm
      - r8a7743-iwg20d-q7

  - job: job-gcc-14-arm-612-cip
    event:
      <<: *kbuild-gcc-14-arm-node-event
      name: kbuild-gcc-14-arm-612-cip
    runtime: *lava-cip-runtime
    platforms: *cip-arm-platforms

  - job: job-gcc-14-arm-61-cip
    event:
      <<: *kbuild-gcc-14-arm-node-event
      name: kbuild-gcc-14-arm-61-cip
    runtime: *lava-cip-runtime
    platforms: *cip-arm-platforms

  - &job-gcc-14-arm-61-cip-rt
    job: job-gcc-14-arm-61-cip-rt
    event:
      <<: *kbuild-gcc-14-arm-node-event
      name: kbuild-gcc-14-arm-61-cip-rt
    runtime: *lava-cip-runtime
    platforms: *cip-arm-platforms

  - <<: *job-gcc-14-arm-61-cip-rt
    job: rt-tests-cyclicdeadline

  - <<: *job-gcc-14-arm-61-cip-rt
    job: rt-tests-cyclictest

  - job: job-gcc-14-arm-510-cip
    event:
      <<: *kbuild-gcc-14-arm-node-event
      name: kbuild-gcc-14-arm-510-cip
    runtime: *lava-cip-runtime
    platforms: *cip-arm-platforms

  - &job-gcc-14-arm-510-cip-rt
    job: job-gcc-14-arm-510-cip-rt
    event:
      <<: *kbuild-gcc-14-arm-node-event
      name: kbuild-gcc-14-arm-510-cip-rt
    runtime: *lava-cip-runtime
    platforms: *cip-arm-platforms

  - <<: *job-gcc-14-arm-510-cip-rt
    job: rt-tests-cyclicdeadline

  - <<: *job-gcc-14-arm-510-cip-rt
    job: rt-tests-cyclictest

  - job: job-gcc-14-arm-419-cip
    event:
      <<: *kbuild-gcc-14-arm-node-event
      name: kbuild-gcc-14-arm-419-cip
    runtime: *lava-cip-runtime
    platforms: *cip-arm-platforms

  - &job-gcc-14-arm-419-cip-rt
    job: job-gcc-14-arm-419-cip-rt
    event:
      <<: *kbuild-gcc-14-arm-node-event
      name: kbuild-gcc-14-arm-419-cip-rt
    runtime: *lava-cip-runtime
    platforms: *cip-arm-platforms

  - <<: *job-gcc-14-arm-419-cip-rt
    job: rt-tests-cyclicdeadline

  - <<: *job-gcc-14-arm-419-cip-rt
    job: rt-tests-cyclictest

  - job: job-gcc-14-arm-419-cip-st
    event:
      <<: *kbuild-gcc-14-arm-node-event
      name: kbuild-gcc-14-arm-419-cip-st
    runtime: *lava-cip-runtime
    platforms:
      - beaglebone-black
      - de0-nano-soc
      - qemu-arm
      - r8a7743-iwg20d-q7

  - job: job-gcc-14-arm-44-cip
    event:
      <<: *kbuild-gcc-14-arm-node-event
      name: kbuild-gcc-14-arm-44-cip
    runtime: *lava-cip-runtime
    platforms: &cip-arm-platforms-44
      - beaglebone-black
      - qemu-arm
      - r8a7743-iwg20d-q7

  - &job-gcc-14-arm-44-cip-rt
    job: job-gcc-14-arm-44-cip-rt
    event:
      <<: *kbuild-gcc-14-arm-node-event
      name: kbuild-gcc-14-arm-44-cip-rt
    runtime: *lava-cip-runtime
    platforms: *cip-arm-platforms-44

  - <<: *job-gcc-14-arm-44-cip-rt
    job: rt-tests-cyclicdeadline

  - <<: *job-gcc-14-arm-44-cip-rt
    job: rt-tests-cyclictest

  - job: job-gcc-14-arm-44-cip-st
    event:
      <<: *kbuild-gcc-14-arm-node-event
      name: kbuild-gcc-14-arm-44-cip-st
    runtime: *lava-cip-runtime
    platforms:
      - beaglebone-black
      - qemu-arm

  - job: kbuild-gcc-14-arm-612-cip
    <<: *build-k8s-all

  - job: kbuild-gcc-14-arm-61-cip
    <<: *build-k8s-all

  - job: kbuild-gcc-14-arm-61-cip-rt
    <<: *build-k8s-all

  - job: kbuild-gcc-14-arm-510-cip
    <<: *build-k8s-all

  - job: kbuild-gcc-14-arm-510-cip-rt
    <<: *build-k8s-all

  - job: kbuild-gcc-14-arm-419-cip
    <<: *build-k8s-all

  - job: kbuild-gcc-14-arm-419-cip-rt
    <<: *build-k8s-all

  - job: kbuild-gcc-14-arm-419-cip-st
    <<: *build-k8s-all

  - job: kbuild-gcc-14-arm-44-cip
    <<: *build-k8s-all

  - job: kbuild-gcc-14-arm-44-cip-rt
    <<: *build-k8s-all

  - job: kbuild-gcc-14-arm-44-cip-st
    <<: *build-k8s-all

# start of CIP riscv scheduler
  - job: job-gcc-14-riscv-612-cip
    event: &kbuild-gcc-14-riscv-node-event
      <<: *node-event-kbuild
      name: kbuild-gcc-14-riscv-612-cip
    runtime: *lava-cip-runtime
    platforms: &cip-riscv-platforms
      - beaglev-fire

  - job: kbuild-gcc-14-riscv-612-cip
    <<: *build-k8s-all

  - job: kbuild-gcc-14-riscv-61-cip
    <<: *build-k8s-all

  - job: kbuild-gcc-14-riscv-510-cip
    <<: *build-k8s-all

# start of CIP x86-64 scheduler
  - job: baseline-x86
    event: &kbuild-gcc-14-x86-node-event
      <<: *node-event-kbuild
      name: kbuild-gcc-14-x86
    runtime: *lava-cip-runtime
    platforms: &cip-x86-platforms
      - qemu
      - x86-openblocks-iot-vx2
      - x86-siemens-mcom
      - x86-simatic-ipc227e

  - job: job-gcc-14-x86-612-cip
    event:
      <<: *kbuild-gcc-14-x86-node-event
      name: kbuild-gcc-14-x86-612-cip
    runtime: *lava-cip-runtime
    platforms: *cip-x86-platforms

  - &job-gcc-14-x86-612-cip-rt
    job: job-gcc-14-x86-612-cip-rt
    event:
      <<: *kbuild-gcc-14-x86-node-event
      name: kbuild-gcc-14-x86-612-cip-rt
    runtime: *lava-cip-runtime
    platforms: *cip-x86-platforms

  - <<: *job-gcc-14-x86-612-cip-rt
    job: rt-tests-cyclicdeadline

  - <<: *job-gcc-14-x86-612-cip-rt
    job: rt-tests-cyclictest

  - job: job-gcc-14-x86-61-cip
    event:
      <<: *kbuild-gcc-14-x86-node-event
      name: kbuild-gcc-14-x86-61-cip
    runtime: *lava-cip-runtime
    platforms: *cip-x86-platforms

  - &job-gcc-14-x86-61-cip-rt
    job: job-gcc-14-x86-61-cip-rt
    event:
      <<: *kbuild-gcc-14-x86-node-event
      name: kbuild-gcc-14-x86-61-cip-rt
    runtime: *lava-cip-runtime
    platforms: *cip-x86-platforms

  - <<: *job-gcc-14-x86-61-cip-rt
    job: rt-tests-cyclicdeadline

  - <<: *job-gcc-14-x86-61-cip-rt
    job: rt-tests-cyclictest

  - job: job-gcc-14-x86-510-cip
    event:
      <<: *kbuild-gcc-14-x86-node-event
      name: kbuild-gcc-14-x86-510-cip
    runtime: *lava-cip-runtime
    platforms: *cip-x86-platforms

  - &job-gcc-14-x86-510-cip-rt
    job: job-gcc-14-x86-510-cip-rt
    event:
      <<: *kbuild-gcc-14-x86-node-event
      name: kbuild-gcc-14-x86-510-cip-rt
    runtime: *lava-cip-runtime
    platforms: *cip-x86-platforms

  - <<: *job-gcc-14-x86-510-cip-rt
    job: rt-tests-cyclicdeadline

  - <<: *job-gcc-14-x86-510-cip-rt
    job: rt-tests-cyclictest

  - job: job-gcc-14-x86-419-cip
    event:
      <<: *kbuild-gcc-14-x86-node-event
      name: kbuild-gcc-14-x86-419-cip
    runtime: *lava-cip-runtime
    platforms: &cip-x86-platforms-419
      - qemu
      - x86-openblocks-iot-vx2
      - x86-simatic-ipc227e

  - &job-gcc-14-x86-419-cip-rt
    job: job-gcc-14-x86-419-cip-rt
    event:
      <<: *kbuild-gcc-14-x86-node-event
      name: kbuild-gcc-14-x86-419-cip-rt
    runtime: *lava-cip-runtime
    platforms: *cip-x86-platforms-419

  - <<: *job-gcc-14-x86-419-cip-rt
    job: rt-tests-cyclicdeadline

  - <<: *job-gcc-14-x86-419-cip-rt
    job: rt-tests-cyclictest

  - job: job-gcc-14-x86-419-cip-st
    event:
      <<: *kbuild-gcc-14-x86-node-event
      name: kbuild-gcc-14-x86-419-cip-st
    runtime: *lava-cip-runtime
    platforms:
      - qemu
      - x86-openblocks-iot-vx2
      - x86-simatic-ipc227e

  - job: job-gcc-14-x86-44-cip
    event:
      <<: *kbuild-gcc-14-x86-node-event
      name: kbuild-gcc-14-x86-44-cip
    runtime: *lava-cip-runtime
    platforms: &cip-x86-platforms-44
      - qemu

  - &job-gcc-14-x86-44-cip-rt
    job: job-gcc-14-x86-44-cip-rt
    event:
      <<: *kbuild-gcc-14-x86-node-event
      name: kbuild-gcc-14-x86-44-cip-rt
    runtime: *lava-cip-runtime
    platforms: *cip-x86-platforms-44

  - <<: *job-gcc-14-x86-44-cip-rt
    job: rt-tests-cyclicdeadline

  - <<: *job-gcc-14-x86-44-cip-rt
    job: rt-tests-cyclictest

  - job: job-gcc-14-x86-44-cip-st
    event:
      <<: *kbuild-gcc-14-x86-node-event
      name: kbuild-gcc-14-x86-44-cip-st
    runtime: *lava-cip-runtime
    platforms:
      - qemu

  - job: kbuild-gcc-14-x86-612-cip
    <<: *build-k8s-all

  - job: kbuild-gcc-14-x86-612-cip-rt
    <<: *build-k8s-all

  - job: kbuild-gcc-14-x86-61-cip
    <<: *build-k8s-all

  - job: kbuild-gcc-14-x86-61-cip-rt
    <<: *build-k8s-all

  - job: kbuild-gcc-14-x86-510-cip
    <<: *build-k8s-all

  - job: kbuild-gcc-14-x86-510-cip-rt
    <<: *build-k8s-all

  - job: kbuild-gcc-14-x86-419-cip
    <<: *build-k8s-all

  - job: kbuild-gcc-14-x86-419-cip-rt
    <<: *build-k8s-all

  - job: kbuild-gcc-14-x86-419-cip-st
    <<: *build-k8s-all

  - job: kbuild-gcc-14-x86-44-cip
    <<: *build-k8s-all

  - job: kbuild-gcc-14-x86-44-cip-rt
    <<: *build-k8s-all

  - job: kbuild-gcc-14-x86-44-cip-st
    <<: *build-k8s-all
