_anchors:

  # Includes all supported architectures.
  base: &base
    tree: mainline
    branch: 'master'

  # Includes most common and/or widely deployed architectures.
  # The 32-bit x86 architecture is considered legacy nowadays,
  # and as such, not included here.
  base-standard: &base-standard
    <<: *base
    architectures:
      - x86_64
      - arm64
      - arm

  # Includes ARM-specific architectures only.
  base-arm: &base-arm
    <<: *base
    architectures:
      - arm64
      - arm

trees:

  # NOTE: Please keep the trees list below in sorted order.

  aaptel:
    url: "https://github.com/aaptel/linux.git"

  amlogic:
    url: "https://git.kernel.org/pub/scm/linux/kernel/git/amlogic/linux.git"

  android:
    url: 'https://android.googlesource.com/kernel/common'

  ardb:
    url: "https://git.kernel.org/pub/scm/linux/kernel/git/ardb/linux.git"

  arm64:
    url: "https://git.kernel.org/pub/scm/linux/kernel/git/arm64/linux.git"

  arnd:
    url: "https://git.kernel.org/pub/scm/linux/kernel/git/arnd/playground.git"

  broonie-misc:
    url: "https://git.kernel.org/pub/scm/linux/kernel/git/broonie/misc.git"

  broonie-regmap:
    url: "https://git.kernel.org/pub/scm/linux/kernel/git/broonie/regmap.git"

  broonie-regulator:
    url: "https://git.kernel.org/pub/scm/linux/kernel/git/broonie/regulator.git"

  broonie-sound:
    url: "https://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git"

  broonie-spi:
    url: "https://git.kernel.org/pub/scm/linux/kernel/git/broonie/spi.git"

  chrome-platform:
    url: "https://git.kernel.org/pub/scm/linux/kernel/git/chrome-platform/linux.git"

  chromiumos:
    url: "https://chromium.googlesource.com/chromiumos/third_party/kernel.git"

  cip:
    url: "https://git.kernel.org/pub/scm/linux/kernel/git/cip/linux-cip.git"

  clk:
    url: "https://git.kernel.org/pub/scm/linux/kernel/git/clk/linux.git"

  collabora-chromeos-kernel:
    url: 'https://gitlab.collabora.com/google/chromeos-kernel.git'

  collabora-next:
    url: 'https://gitlab.collabora.com/kernel/collabora-next.git'

  efi:
    url: "https://git.kernel.org/pub/scm/linux/kernel/git/efi/efi.git"

  hyperv:
    url: "https://git.kernel.org/pub/scm/linux/kernel/git/hyperv/linux.git"

  kernelci:
    url: "https://github.com/kernelci/linux.git"

  khilman:
    url: "https://git.kernel.org/pub/scm/linux/kernel/git/khilman/linux.git"

  krzysztof:
    url: "https://git.kernel.org/pub/scm/linux/kernel/git/krzk/linux.git"

  kselftest:
    url: 'https://git.kernel.org/pub/scm/linux/kernel/git/shuah/linux-kselftest.git'

  lee-backlight:
    url: "https://git.kernel.org/pub/scm/linux/kernel/git/lee/backlight.git"

  lee-mfd:
    url: "https://git.kernel.org/pub/scm/linux/kernel/git/lee/mfd.git"

  linusw:
    url: "https://git.kernel.org/pub/scm/linux/kernel/git/linusw/linux-gpio.git"

  linux-pci:
    url: "https://git.kernel.org/pub/scm/linux/kernel/git/pci/pci.git"

  mainline:
    url: 'https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git'

  media-committers:
    url: 'https://gitlab.freedesktop.org/linux-media/media-committers.git'

  media:
    url: 'https://git.linuxtv.org/media.git'

  mediatek:
    url: 'https://git.kernel.org/pub/scm/linux/kernel/git/mediatek/linux.git'

  net-next:
    url: "https://git.kernel.org/pub/scm/linux/kernel/git/netdev/net-next.git"

  netdev-testing:
    url: "https://github.com/linux-netdev/testing.git"

  next:
    url: 'https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git'

  omap:
    url: "https://git.kernel.org/pub/scm/linux/kernel/git/khilman/linux-omap.git"

  padovan:
    url: "https://github.com/padovan/linux.git"

  pm:
    url: "https://git.kernel.org/pub/scm/linux/kernel/git/rafael/linux-pm.git"

  qcom:
    url: "https://git.kernel.org/pub/scm/linux/kernel/git/qcom/linux.git"

  renesas:
    url: "https://git.kernel.org/pub/scm/linux/kernel/git/geert/renesas-devel.git"

  riscv:
    url: "https://git.kernel.org/pub/scm/linux/kernel/git/riscv/linux.git"

  robh:
    url: "https://git.kernel.org/pub/scm/linux/kernel/git/robh/linux.git"

  rppt:
    url: "https://git.kernel.org/pub/scm/linux/kernel/git/rppt/memblock.git"

  sashal-next:
    url: "https://git.kernel.org/pub/scm/linux/kernel/git/sashal/linus-next.git"

  soc:
    url: "https://git.kernel.org/pub/scm/linux/kernel/git/soc/soc.git"

  stable-rc:
    url: 'https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git'

  stable-rt:
    url: 'https://git.kernel.org/pub/scm/linux/kernel/git/rt/linux-stable-rt.git'

  stable:
    url: 'https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git'

  tegra:
    url: "https://git.kernel.org/pub/scm/linux/kernel/git/tegra/linux.git"

  thermal:
    url: "https://git.kernel.org/pub/scm/linux/kernel/git/thermal/linux.git"

  tip:
    url: "https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git"

  ulfh:
    url: "https://git.kernel.org/pub/scm/linux/kernel/git/ulfh/mmc.git"

  vireshk:
    url: "https://git.kernel.org/pub/scm/linux/kernel/git/vireshk/linux.git"

# -----------------------------------------------------------------------------
# Legacy configuration data (still used by trigger service)
#

build_environments:

  gcc-12:
    cc: gcc
    cc_version: 10
    arch_params:
      x86_64:
        name: 'x86'


build_variants:
  variants:
    gcc-12:
      build_environment: gcc-12
      architectures:
        x86_64:
          base_defconfig: 'x86_64_defconfig'
          filters:
            - regex: { defconfig: 'x86_64_defconfig' }
        arm64:
          base_defconfig: 'defconfig'
          filters:
            - regex: { defconfig: 'defconfig' }
        arm:
          base_defconfig: 'multi_v7_defconfig'
          filters:
            - regex: { defconfig: 'multi_v7_defconfig' }


build_configs:

  # NOTE: Please keep the trees list below in sorted order.

  aaptel:
    <<: *base-standard
    tree: aaptel
    branch: 'nvme-rx-offload-ci'

  amlogic:
    <<: *base-arm
    tree: amlogic
    branch: 'for-next'

  android_mainline: &android
    tree: android
    branch: 'android-mainline'
    architectures:
      - x86_64
      - i386
      - arm64
      - arm
      - riscv
      - um

  android_mainline_tracking:
    <<: *android
    branch: 'android-mainline-tracking'

  android11-5.4:
    <<: *android
    branch: 'android11-5.4'

  android12-5.4:
    <<: *android
    branch: 'android12-5.4'

  android12-5.4-lts:
    <<: *android
    branch: 'android12-5.4-lts'

  android12-5.10:
    <<: *android
    branch: 'android12-5.10'

  android12-5.10-lts:
    <<: *android
    branch: 'android12-5.10-lts'

  android13-5.10:
    <<: *android
    branch: 'android13-5.10'

  android13-5.10-lts:
    <<: *android
    branch: 'android13-5.10-lts'

  android13-5.15:
    <<: *android
    branch: 'android13-5.15'

  android13-5.15-lts:
    <<: *android
    branch: 'android13-5.15-lts'

  android14-5.15:
    <<: *android
    branch: 'android14-5.15'

  android14-5.15-lts:
    <<: *android
    branch: 'android14-5.15-lts'

  android14-6.1:
    <<: *android
    branch: 'android14-6.1'

  android14-6.1-lts:
    <<: *android
    branch: 'android14-6.1-lts'

  android15-6.6:
    <<: *android
    branch: 'android15-6.6'

  android15-6.6-lts:
    <<: *android
    branch: 'android15-6.6-lts'

  android16-6.12:
    <<: *android
    branch: 'android16-6.12'

  ardb:
    <<: *base-standard
    tree: ardb
    branch: 'for-kernelci'

  arm64:
    tree: arm64
    branch: 'for-kernelci'
    architectures:
      - arm64

  arnd:
    <<: *base-standard
    tree: arnd
    branch: 'to-build'

  broonie: &broonie
    <<: *base-standard

  broonie-misc:
    <<: *broonie
    tree: broonie-misc
    branch: 'for-kernelci'

  broonie-regmap:
    <<: *broonie
    tree: broonie-regmap
    branch: 'for-next'

  broonie-regmap-fixes:
    <<: *broonie
    tree: broonie-regmap
    branch: 'for-linus'

  broonie-regulator:
    <<: *broonie
    tree: broonie-regulator
    branch: 'for-next'

  broonie-regulator-fixes:
    <<: *broonie
    tree: broonie-regulator
    branch: 'for-linus'

  broonie-sound:
    <<: *broonie
    tree: broonie-sound
    branch: 'for-next'

  broonie-sound-fixes:
    <<: *broonie
    tree: broonie-sound
    branch: 'for-linus'

  broonie-spi:
    <<: *broonie
    tree: broonie-spi
    branch: 'for-next'

  broonie-spi-fixes:
    <<: *broonie
    tree: broonie-spi
    branch: 'for-linus'

  chrome-platform: &chrome-platform
    <<: *base-standard
    tree: chrome-platform
    branch: 'for-next'

  chrome-platform-firmware:
    <<: *chrome-platform
    branch: 'for-firmware-next'

  chromiumos: &chromiumos
    <<: *base-standard
    tree: chromiumos

  chromiumos-5.4:
    <<: *chromiumos
    branch: 'chromeos-5.4'

  chromiumos-5.10:
    <<: *chromiumos
    branch: 'chromeos-5.10'

  chromiumos-5.15:
    <<: *chromiumos
    branch: 'chromeos-5.15'

  chromiumos-6.1:
    <<: *chromiumos
    branch: 'chromeos-6.1'

  chromiumos-6.6:
    <<: *chromiumos
    branch: 'chromeos-6.6'

  chromiumos-6.12:
    <<: *chromiumos
    branch: 'chromeos-6.12'

  cip-4.4: &cip
    <<: *base
    tree: cip
    branch: 'linux-4.4.y-cip'

  cip-4.4-rt:
    <<: *cip
    branch: 'linux-4.4.y-cip-rt'

  cip-4.4-st:
    <<: *cip
    branch: 'linux-4.4.y-st'

  cip-4.19:
    <<: *cip
    branch: 'linux-4.19.y-cip'

  cip-4.19-rt:
    <<: *cip
    branch: 'linux-4.19.y-cip-rt'

  cip-4.19-st:
    <<: *cip
    branch: 'linux-4.19.y-st'

  cip-5.10:
    <<: *cip
    branch: 'linux-5.10.y-cip'

  cip-5.10-rt:
    <<: *cip
    branch: 'linux-5.10.y-cip-rt'

  cip-6.1:
    <<: *cip
    branch: 'linux-6.1.y-cip'

  cip-6.1-rt:
    <<: *cip
    branch: 'linux-6.1.y-cip-rt'

  clk:
    <<: *base-arm
    tree: clk
    branch: 'clk-next'

  collabora-chromeos-kernel_for-kernelci: &collabora
    <<: *base-standard
    branch: 'for-kernelci'
    tree: collabora-chromeos-kernel

  collabora-next_for-kernelci:
    <<: *collabora
    tree: collabora-next

  efi:
    <<: *base-standard
    tree: efi
    branch: 'next'

  hyperv-next: &hyperv
    <<: *base-standard
    tree: hyperv
    branch: 'hyperv-next'
    architectures:
      - x86_64

  hyperv-fixes:
    <<: *hyperv
    branch: 'hyperv-fixes'

  kernelci_staging-mainline: &kernelci
    <<: *base-standard
    tree: kernelci
    branch: 'staging-mainline'

  kernelci_staging-next:
    <<: *kernelci
    branch: 'staging-next'

  kernelci_staging-stable:
    <<: *kernelci
    branch: 'staging-stable'

  khilman:
    <<: *base-arm
    tree: khilman
    branch: 'to-build'

  krzysztof:
    <<: *base-arm
    tree: krzysztof
    branch: 'for-next'

  kselftest_fixes: &kselftest
    <<: *base
    tree: kselftest
    branch: 'fixes'

  kselftest_next:
    <<: *kselftest
    branch: 'next'

  lee_backlight: &lee
    <<: *base-standard
    tree: lee-backlight
    branch: 'for-backlight-next'

  lee_mfd:
    <<: *lee
    tree: lee-mfd
    branch: 'for-mfd-next'

  linusw: &linusw
    <<: *base-arm
    tree: linusw

  linusw_devel:
    <<: *linusw
    branch: 'devel'

  linusw_fixes:
    <<: *linusw
    branch: 'fixes'

  linusw_for-next:
    <<: *linusw
    branch: 'for-next'

  linux-pci_next: &linux-pci
    tree: linux-pci
    branch: 'next'
    architectures:
      - x86_64
      - arm64
      - arm

  linux-pci_for-linus:
    <<: *linux-pci
    branch: 'for-linus'

  linux-pci_for-kernelci:
    <<: *linux-pci
    branch: 'for-kernelci'

  mainline:
    <<: *base
    tree: mainline
    branch: 'master'

  media-committers_fixes: &media-committers
    <<: *base-standard
    tree: media-committers
    branch: 'fixes'

  media-committers_next:
    <<: *media-committers
    branch: 'next'

  media_fixes: &media
    <<: *base-standard
    tree: media
    branch: 'fixes'

  media_next:
    <<: *media
    branch: 'next'

  mediatek_for_next:
    <<: *base-arm
    tree: mediatek
    branch: 'for-next'

  net-next:
    <<: *base
    tree: net-next
    branch: 'main'

  netdev-testing:
    <<: *base
    tree: netdev-testing
    branch: 'https://netdev.bots.linux.dev/static/nipa/branches-hw.json'

  next_master: &next
    <<: *base
    tree: next

  next_pending-fixes:
    <<: *next
    branch: 'pending-fixes'

  omap:
    <<: *base-arm
    tree: omap
    branch: 'for-next'

  padovan:
    <<: *base-standard
    tree: padovan
    branch: 'for-kernelci'

  pm:
    <<: *base-standard
    tree: pm
    branch: 'testing'

  qcom:
    <<: *base-arm
    tree: qcom
    branch: 'for-next'

  renesas: &renesas
    <<: *base-arm
    tree: renesas

  renesas_next:
    <<: *renesas
    branch: 'next'

  riscv_fixes: &riscv
    tree: riscv
    branch: 'fixes'
    architectures:
      - riscv

  riscv_for-next:
    <<: *riscv
    branch: 'for-next'

  robh:
    <<: *base-standard
    tree: robh
    branch: 'for-kernelci'

  rppt:
    <<: *base-standard
    tree: rppt
    branch: 'for-kernelci'

  sashal-next:
    <<: *base
    tree: sashal-next
    branch: 'linus-next'

  soc_fixes: &soc
    <<: *base-arm
    tree: soc
    branch: 'arm/fixes'

  soc_for-next:
    <<: *soc
    branch: 'for-next'

  stable-rc_5.4: &stable-rc
    <<: *stable-rc
    <<: *base
    tree: stable-rc
    branch: 'linux-5.4.y'

  stable-rc_5.10:
    <<: *stable-rc
    branch: 'linux-5.10.y'

  stable-rc_5.15:
    <<: *stable-rc
    branch: 'linux-5.15.y'

  stable-rc_6.1:
    <<: *stable-rc
    branch: 'linux-6.1.y'

  stable-rc_6.6:
    <<: *stable-rc
    branch: 'linux-6.6.y'

  stable-rc_6.7:
    <<: *stable-rc
    branch: 'linux-6.7.y'

  stable-rc_6.9:
    <<: *stable-rc
    branch: 'linux-6.9.y'

  stable-rc_6.10:
    <<: *stable-rc
    branch: 'linux-6.10.y'

  stable-rc_6.11:
    <<: *stable-rc
    branch: 'linux-6.11.y'

  stable-rc_6.12:
    <<: *stable-rc
    branch: 'linux-6.12.y'

  stable-rc_6.13:
    <<: *stable-rc
    branch: 'linux-6.13.y'

  stable-rc_6.14:
    <<: *stable-rc
    branch: 'linux-6.14.y'

  stable-rt_v4.14-rt: &stable-rt
    <<: *base
    tree: stable-rt
    branch: 'v4.14-rt'

  stable-rt_v4.14-rt-next:
    <<: *stable-rt
    branch: 'v4.14-rt-next'

  stable-rt_v5.4-rt:
    <<: *stable-rt
    branch: 'v5.4-rt'

  stable-rt_v5.10-rt:
    <<: *stable-rt
    branch: 'v5.10-rt'

  stable-rt_v5.10-rt-next:
    <<: *stable-rt
    branch: 'v5.10-rt-next'

  stable-rt_v5.15-rt:
    <<: *stable-rt
    branch: 'v5.15-rt'

  stable-rt_v5.15-rt-next:
    <<: *stable-rt
    branch: 'v5.15-rt-next'

  stable-rt_v6.1-rt:
    <<: *stable-rt
    branch: 'v6.1-rt'

  stable-rt_v6.1-rt-next:
    <<: *stable-rt
    branch: 'v6.1-rt-next'

  stable-rt_v6.6-rt:
    <<: *stable-rt
    branch: 'v6.6-rt'

  stable_5.4: &stable
    <<: *base
    tree: stable
    branch: 'linux-5.4.y'

  stable_5.10:
    <<: *stable
    branch: 'linux-5.10.y'

  stable_5.15:
    <<: *stable
    branch: 'linux-5.15.y'

  stable_6.1:
    <<: *stable
    branch: 'linux-6.1.y'

  stable_6.6:
    <<: *stable
    branch: 'linux-6.6.y'

  stable_6.12:
    <<: *stable
    branch: 'linux-6.12.y'

  stable_6.13:
    <<: *stable
    branch: 'linux-6.13.y'

  stable_6.14:
    <<: *stable
    branch: 'linux-6.14.y'

  tegra:
    <<: *base-arm
    tree: tegra
    branch: 'for-next'

  thermal:
    <<: *base-standard
    tree: thermal
    branch: 'testing'

  tip:
    <<: *base-standard
    tree: tip

  ulfh:
    <<: *base-standard
    tree: ulfh
    branch: 'next'

  vireshk:
    <<: *base-standard
    tree: vireshk
    branch: 'for-kernelci'
