build_configs:
  stable_5.4: &stable
    tree: stable
    branch: 'linux-5.4.y'
    priority: high

  stable_5.10:
    <<: *stable
    branch: 'linux-5.10.y'

  stable_5.15:
    <<: *stable
    branch: 'linux-5.15.y'

  stable_6.1:
    <<: *stable
    branch: 'linux-6.1.y'

  stable_6.6:
    <<: *stable
    branch: 'linux-6.6.y'

  stable_6.12:
    <<: *stable
    branch: 'linux-6.12.y'

  stable_6.13:
    <<: *stable
    branch: 'linux-6.13.y'

  stable_6.14:
    <<: *stable
    branch: 'linux-6.14.y'
