build_configs:
  stable-rt_v4.14-rt: &stable-rt
    tree: stable-rt
    branch: 'v4.14-rt'
    priority: medium

  stable-rt_v4.14-rt-next:
    <<: *stable-rt
    branch: 'v4.14-rt-next'

  stable-rt_v5.4-rt:
    <<: *stable-rt
    branch: 'v5.4-rt'

  stable-rt_v5.10-rt:
    <<: *stable-rt
    branch: 'v5.10-rt'

  stable-rt_v5.10-rt-next:
    <<: *stable-rt
    branch: 'v5.10-rt-next'

  stable-rt_v5.15-rt:
    <<: *stable-rt
    branch: 'v5.15-rt'

  stable-rt_v5.15-rt-next:
    <<: *stable-rt
    branch: 'v5.15-rt-next'

  stable-rt_v6.1-rt:
    <<: *stable-rt
    branch: 'v6.1-rt'

  stable-rt_v6.1-rt-next:
    <<: *stable-rt
    branch: 'v6.1-rt-next'

  stable-rt_v6.6-rt:
    <<: *stable-rt
    branch: 'v6.6-rt'
