build_configs:
  stable-rc_5.10: &stable-rc
    tree: stable-rc
    branch: 'linux-5.10.y'

  stable-rc_5.15:
    <<: *stable-rc
    branch: 'linux-5.15.y'

  stable-rc_6.1:
    <<: *stable-rc
    branch: 'linux-6.1.y'

  stable-rc_6.6:
    <<: *stable-rc
    branch: 'linux-6.6.y'

  stable-rc_6.12:
    <<: *stable-rc
    branch: 'linux-6.12.y'

  stable-rc_6.18:
    <<: *stable-rc
    branch: 'linux-6.18.y'
